<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>Laporan Penjualan</title>

    <style>

        body{
            font-family: DejaVu Sans, sans-serif;
            font-size:12px;
            color:#333;
            margin:35px;
        }

        .header{
            text-align:center;
            border-bottom:2px solid #2563eb;
            padding-bottom:15px;
            margin-bottom:20px;
        }

        .header h1{
            margin:0;
            font-size:28px;
            color:#2563eb;
        }

        .header p{
            margin:4px 0;
            color:#666;
        }

        .title{
            text-align:center;
            margin:25px 0;
            font-size:18px;
            font-weight:bold;
            text-transform:uppercase;
        }

        .info{
            width:100%;
            margin-bottom:20px;
        }

        .info td{
            border:none;
            padding:4px 0;
            font-size:13px;
        }

        table{
            width:100%;
            border-collapse:collapse;
        }

        th{
            background:#2563eb;
            color:white;
            padding:10px;
            border:1px solid #d1d5db;
        }

        td{
            padding:9px;
            border:1px solid #d1d5db;
        }

        .center{
            text-align:center;
        }

        .right{
            text-align:right;
        }

        .summary{
            width:40%;
            margin-top:20px;
            margin-left:auto;
            border-collapse:collapse;
        }

        .summary th{
            background:#f3f4f6;
            color:#000;
        }

        .summary td,
        .summary th{
            border:1px solid #ccc;
            padding:8px;
        }

        .footer{
            margin-top:60px;
            border-top:1px solid #ccc;
            padding-top:10px;
            text-align:center;
            color:#666;
            font-size:11px;
        }

    </style>

</head>

<body>

<div class="header">

    <h1>STEVENtix</h1>

    <p>Event & Ticketing Management System</p>

</div>

<div class="title">

    LAPORAN PENJUALAN EVENT

</div>

<table class="info">

<tr>

<td width="18%"><strong>Organizer</strong></td>

<td>: {{ $organizer->nama_organizer }}</td>

</tr>

<tr>

<td><strong>Tanggal Cetak</strong></td>

<td>: {{ now()->format('d F Y H:i') }}</td>

</tr>

</table>

<table>

<thead>

<tr>

<th width="6%">No</th>

<th>Nama Event</th>

<th width="16%">Tanggal</th>

<th width="15%">Status</th>

<th width="12%">Tiket</th>

<th width="18%">Pendapatan</th>

</tr>

</thead>

<tbody>

@foreach($events as $index=>$event)

<tr>

<td class="center">

{{ $index+1 }}

</td>

<td>

{{ $event->nama_event }}

</td>

<td class="center">

{{ \Carbon\Carbon::parse($event->tanggal)->format('d M Y') }}

</td>

<td class="center">

@if($event->status=='approved')

Aktif

@elseif($event->status=='pending')

Menunggu ACC

@else

Ditolak

@endif

</td>

<td class="center">

{{ $event->tiket_terjual }}

</td>

<td class="right">

Rp{{ number_format($event->pendapatan,0,',','.') }}

</td>

</tr>

@endforeach

</tbody>

</table>

<table class="summary">

<tr>

<th>Total Tiket</th>

<td class="right">

{{ $totalTiketTerjual }}

</td>

</tr>

<tr>

<th>Total Pendapatan</th>

<td class="right">

<strong>

Rp{{ number_format($totalPendapatan,0,',','.') }}

</strong>

</td>

</tr>

</table>

<div class="footer">

Generated by <strong>STEVENtix</strong><br>

Laporan ini dibuat secara otomatis oleh sistem.

</div>

</body>

</html>